sudo: false
language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
matrix:
  allow_failures:
  - php: '5.6'
  - php: hhvm

services:
  - postgresql

addons:
  apt:
    packages:
    - python-pip
    - firefox
    - xvfb

before_install:
  - mkdir ~/.ffmpeg
  - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O ~/.ffmpeg/ffmpeg.tar.xz
  - tar -xf ~/.ffmpeg/ffmpeg.tar.xz -C ~/.ffmpeg --strip=1
  - export PATH=~/.ffmpeg:$PATH
  - nvm install 6
  - psql -c 'create database travis_ci_test;' -U postgres
  - openssl aes-256-cbc -K $encrypted_5f496bf5950e_key -iv $encrypted_5f496bf5950e_iv -in .env.travis.enc -out .env -d
install:
  - composer create-project
  - npm install
  - pip install --user cfscrape==1.7.1
  - pip install --user selenium
  - php artisan migrate --seed
  - node ./node_modules/gulp/bin/gulp.js --production
before_script:
  - php -v
  - npm -v
  - node -v
  - python -V
  - pip list
  - ffmpeg -version
  - firefox -v

cache:
  pip: true
  directories:
  - vendor
  - node_modules
